from __future__ import annotations

from typing import Final

WEBAGENT_RUN_TYPES: Final[set[str]] = {
    "scrape",
    "web-discovery",
    "web-explorer",
    "web-test",
    "security-scan",
    "browse",
    "test",
    "form-fill",
    "upload-test",
    "deep-explore",
    "qa-audit",
    "extraction-only",
    "autonomous-task",
}

WEBAGENT_RUN_TYPE_ALIASES: Final[dict[str, str]] = {
    "discovery-scan": "web-discovery",
    "content-extract": "scrape",
    "form-intel": "web-test",
    "upload-validation": "web-test",
    "workflow-e2e": "web-test",
    "full-automation": "web-test",
    "form-automation": "form-fill",
    "e2e-workflow": "test",
    "interactive-automation": "test",
    "quick-scan": "web-discovery",
    "site-map": "web-discovery",
    "content-scrape": "scrape",
    "security-baseline": "security-scan",
    "deep-interaction": "deep-explore",
}

PLAYWRIGHT_ACTION_ALIASES: Final[dict[str, str]] = {
    "navigate": "goto",
    "upload": "set_input_files",
    "select": "select_option",
    "wait_for": "wait_for_selector",
    "status": "session_status",
    "close_session": "stop_session",
    "new_tab": "new_page",
    "switch_tab": "switch_page",
    "close_tab": "close_page",
    "refresh": "reload",
    "double_click": "dblclick",
    "right_click": "click",
    "keyboard_type": "keyboard_type",
    "keyboard_press": "press",
}

PLAYWRIGHT_ACTIONS: Final[set[str]] = {
    # Session/navigation
    "start_session",
    "stop_session",
    "session_status",
    "goto",
    "go_back",
    "go_forward",
    "reload",
    "wait_for_load_state",
    "wait_for_selector",
    "wait_for_timeout",
    "new_page",
    "switch_page",
    "close_page",
    # Interaction
    "click",
    "dblclick",
    "hover",
    "focus",
    "blur",
    "drag_and_drop",
    "fill",
    "type",
    "keyboard_type",
    "press",
    "check",
    "uncheck",
    "select_option",
    "set_input_files",
    "dispatch_event",
    "scroll",
    "scroll_into_view",
    "interact_iframe",
    "interact_shadow",
    # Extraction/capture
    "screenshot",
    "pdf",
    "capture_html",
    "capture_text",
    "extract",
    "accessibility_snapshot",
    "network_log",
    "console_log",
    "js_errors",
    "performance_timing",
    "dom_summary",
    "inventory_actions",
    "inventory_forms",
    "inventory_uploads",
    "discover_navigation",
    "discover_modals",
    "discover_iframes",
    "scan_page",
    # Analysis/report
    "summarize_page",
    "summarize_run",
    "analyze_form",
    "analyze_upload_flow",
    "analyze_failures",
    # Validation
    "assert_text_present",
    "assert_selector_present",
    "assert_upload_success",
    "assert_navigation_happened",
    "assert_console_clean",
    "assert_no_js_errors",
    "assert_file_preview_visible",
    # Export
    "export_run_json",
    "export_run_markdown",
    "export_artifacts_bundle",
    # Utility
    "evaluate",
    "generate_test_asset",
    "upload_test_asset",
    "upload_matrix_test",
    "fill_form",
    "fill_all_forms",
    "deep_explore_page",
    "deep_explore_site",
}

DESTRUCTIVE_KEYWORDS: Final[tuple[str, ...]] = (
    "delete",
    "remove",
    "logout",
    "sign out",
    "submit",
    "purchase",
    "pay",
    "reset",
    "uninstall",
    "disconnect",
    "destroy",
    "drop",
    "cancel account",
    "close account",
)

SESSION_OPTIONAL_ACTIONS: Final[set[str]] = {
    "start_session",
    "session_status",
    "generate_test_asset",
    "scan_page",
    "summarize_run",
    "export_run_json",
    "export_run_markdown",
}

TOOL_TO_ACTION: Final[dict[str, str]] = {
    "open_url": "goto",
    "visit_sequence": "goto",
    "revisit_with_profile": "goto",
    "scan_page": "scan_page",
    "inventory_actions": "inventory_actions",
    "inventory_forms": "inventory_forms",
    "inventory_uploads": "inventory_uploads",
    "discover_navigation": "discover_navigation",
    "discover_modals": "discover_modals",
    "discover_iframes": "discover_iframes",
    "interact_element": "click",
    "interact_by_text": "click",
    "interact_by_role": "click",
    "interact_by_selector": "click",
    "fill_form": "fill_form",
    "fill_all_forms": "fill_all_forms",
    "deep_explore_page": "deep_explore_page",
    "deep_explore_site": "deep_explore_site",
    "generate_test_asset": "generate_test_asset",
    "upload_test_asset": "upload_test_asset",
    "upload_matrix_test": "upload_matrix_test",
    "screenshot_page": "screenshot",
    "screenshot_element": "screenshot",
    "capture_html": "capture_html",
    "capture_text": "capture_text",
    "capture_network": "network_log",
    "capture_console": "console_log",
    "capture_trace": "export_artifacts_bundle",
    "summarize_page": "summarize_page",
    "summarize_run": "summarize_run",
    "analyze_form": "analyze_form",
    "analyze_upload_flow": "analyze_upload_flow",
    "analyze_failures": "analyze_failures",
    "assert_text_present": "assert_text_present",
    "assert_selector_present": "assert_selector_present",
    "assert_upload_success": "assert_upload_success",
    "assert_navigation_happened": "assert_navigation_happened",
    "assert_console_clean": "assert_console_clean",
    "assert_no_js_errors": "assert_no_js_errors",
    "assert_file_preview_visible": "assert_file_preview_visible",
    "export_run_json": "export_run_json",
    "export_run_markdown": "export_run_markdown",
    "export_artifacts_bundle": "export_artifacts_bundle",
}
